### ISSUE TITLE
UTF-8 encoding?

### ISSUE THREAD

**Issue by JohnRodney** [frozeman/meteor-build-client#35] opened 2016-08-01 16:36 UTC
Hey I'm working with this repository to export the meteor client of an app and inject it into a dom using a chrome extension.  The build `2983439aeeb382.js` file is throwing an error that it is not utf-8 encoded when trying to inject as a content script.

Is this a side effect of the meteor build itself or something I can be in control of with this build?

Thanks for your time.

**Comment by jankapunkt** [comment] 2018-09-18 15:29
I think the build is just missing the `<meta charset="utf-8" /> ` in the `<head>` section. Just add it manually after you have built and should be fine.

**Comment by dr-dimitru** [comment] 2020-06-01 13:30
This issue was addressed in one of previous releases, now if no custom `<head>` element is found default `<head><meta charset="utf-8"></head>` is injected into generated `index.html`

Feel free to reopen it in case if the issue is still persists on your end.

**Closed by dr-dimitru** 2020-06-01 13:30 UTC

**Comment by dr-dimitru** [comment] 2020-08-12 11:16
Hello @JohnRodney,

Thank you for pointing this out!
Implemented as part of [`v1.0.0`](https://github.com/frozeman/meteor-build-client/releases/tag/1.0.0), and published last night to [NPM](http://npmjs.com/package/meteor-build-client). Please, give it a try and let me know if there's any issues.
