### ISSUE TITLE
How get Server URL dynamically at run time via server environment variable  

### ISSUE THREAD

**Issue by AnjaniKumar15** [frozeman/meteor-build-client#37] opened 2016-10-20 13:54 UTC
Please suggest me how get server URL dynamically at run time via server environment variable.

**Comment by frozeman** [comment] 2016-10-20 14:02
I don't know from the top of my head. Please refer to the npm docs for this

**Comment by AnjaniKumar15** [comment] 2016-10-20 14:29
Actually I am using your package to build my meteor client application. if I had provided meteor server URL at build time then it works fine, but I want to give meteor server URL at run time dynamically (ex. environment variable) then Is any way to do this thing? 
Its required because we have two Meteor admin servers and I want, when I change URL path of my client app hosted server environment variable, My meteor Client app redirect and connect with other server.

**Comment by dr-dimitru** [comment] 2020-10-02 19:58
Hello @AnjaniKumar15,

I'm afraid it would not possible as server URL is hardcoded into `__meteor_runtime_config__ ` [from `settings` Object](https://github.com/frozeman/meteor-build-client/blob/master/meteor.js#L281);

You can replace server's URL in generated `index.html` template with needed value before serving it to user on NGINX or whatever server you're using.

**Comment by dr-dimitru** [comment] 2022-06-14 14:32
Ran through the thread, years later I still think you should go with two builds with different settings

Feel free to close it in case if the issue is solved on your end.

**Closed by dr-dimitru** 2022-06-14 14:32 UTC
Labels: question
